import "~/styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "~/components/navbar/navbar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${inter.variable}`}>
			<body>
				<TRPCReactProvider>
					<Navbar />
					<div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#cdd193] to-[#478c5c] text-primary">
						{children}
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
